apiVersion: v1
kind: Service
metadata:
  name: {{ include "totpvault.fullname" . }}
  labels:
    {{- include "totpvault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "totpvault.app.selectorLabels" . | nindent 4 }}
